# Important Notes:
# Every field you add must be added to the root build.gradle.kts expandProps map.
# Project
version=1.2
group=at.alex
java_version=21
# Common
mod_name=Time & Weather Changer
mod_author=Alex_265
mod_id=timechanger
license=BSD-2-Clause
credits=
description=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
